# Generated by Django 5.2.4 on 2025-07-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
