# Generated by Django 5.2.4 on 2025-07-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0002_rename_user_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
